[package]
name = "prometheus-mqtt-transport"
version = "0.1.0-20221222"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "prometheus-fetch"
path = "src/prometheus-fetch/main.rs"

[[bin]]
name = "mqtt-export"
path = "src/mqtt-export/main.rs"

[lib]
name = "global"
path = "src/global/lib.rs"

# [[lib]]
# name = "mqtt"
# path = "src/mqtt/lib.rs"

[dependencies]

